build:
  image: $$IMAGE
  pull: true
  commands:
    - |
      case "${IMAGE}" in
        *centos*)
          yum -y update
          yum -y install make gcc
          ;;
        *ubuntu*|*debian*)
          apt-get update
          apt-get install make gcc
          ;;
      esac
    - make

matrix:
  IMAGE:
    - library/centos:6
    - library/centos:7
    - library/ubuntu:12.04
    - library/ubuntu:14.04
    - library/ubuntu:15.10
    - library/ubuntu:16.04
